trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: Run Pester (.ps1)
  inputs:
    targetType: 'inline'
    script: './build.ps1 -Test'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: './build.ps1 -Compile'

- task: PowerShell@2
  displayName: Run Pester (.pms1)
  inputs:
    targetType: 'inline'
    script: './build.ps1 -Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults.xml'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'AzSpeedOps'
    targetPath: './'